@startuml
描述语言 -> 步骤: Cucumber 驱动描述语言调用步骤代码
步骤 -> 行为: 对行为进行组装, 并形成步骤
行为 -> 页面: 直接调用页面, 形成业务相关行为
页面 -> 行为: 页面变化
行为 -> 步骤: 反馈行为结果
步骤 -> 描述语言: 断言最终结果
描述语言 -> 监听: 描述语言根据结果反馈给监听器
监听 -> 观察者: 将最后结果反馈给观察者
@enduml